# Generated by Django 3.2.16 on 2022-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20221022_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='https://cs9.pikabu.ru/post_img/big/2019/10/30/10/1572455476123442192.jpg'),
            preserve_default=False,
        ),
    ]
